matrix:
  include:
    language: node_js
    node_js: "10"

cache:
  directories:
    - node_modules

script:
  - npm install
  - npm run electron:build
  - cd dist_electron
  - cd win-unpacked

branches:
  except:
    - "/^v\\d+\\.\\d+\\.\\d+$/"